In [1]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import matplotlib.pyplot as plt
import gc
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, RandomizedSearchCV, cross_val_predict, cross_validate
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score, RocCurveDisplay, f1_score, recall_score, roc_curve, auc, ConfusionMatrixDisplay, make_scorer, balanced_accuracy_score 
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler, RobustScaler
from sklearn.impute import SimpleImputer
import timeit
import time
import xgboost as xgb
import lightgbm as lgb
from sklearn.model_selection import TimeSeriesSplit, StratifiedGroupKFold
import mlflow
from sklearn.utils.class_weight import compute_sample_weight
import pathlib

In [2]:
# Set up mlflow connection with database
mlflow.set_tracking_uri("postgresql://postgres:mars2006@localhost:5432/mlflow_oil_logging")

mlflow.set_experiment("Oil_Well_Fault_Detection")

<Experiment: artifact_location='/Users/Tari/Desktop/Tari/oil_dataset/predictive_maintenance_dataset/notebooks/mlruns/1', creation_time=1789848169371, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1789848169371, lifecycle_stage='active', name='Oil_Well_Fault_Detection', tags={}, trace_location=None, workspace='default'>

In [3]:
mlflow.autolog(silent=True,disable=True)

In [5]:
pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.13.tar.gz (378 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (pyproject.toml) ... done
  Created wheel for psycopg2: filename=psycopg2-2.9.13-cp314-cp314-macosx_12_0_arm64.whl size=133947 sha256=29f103889cc26dc60ea0a0e184e6ee51e4bae79e5ce7eeb6b3477f3b55b0df83
  Stored in directory: /Users/Tari/Library/Caches/pip/wheels/6d/13/0d/e7151d6c5695aab4ae1e34a9151233d8522ea9bdfda8ffddae
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.13
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install --upgrade "mlflow>=3.1"

Collecting mlflow>=3.1
  Downloading mlflow-3.16.1-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-skinny==3.16.1 (from mlflow>=3.1)
  Downloading mlflow_skinny-3.16.1-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-tracing==3.16.1 (from mlflow>=3.1)
  Downloading mlflow_tracing-3.16.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow>=3.1)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Collecting Flask<4 (from mlflow>=3.1)
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting aiohttp<4,>=3.7.0 (from mlflow>=3.1)
  Downloading aiohttp-3.14.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (8.3 kB)
Collecting alembic!=1.10.0,<2 (from mlflow>=3.1)
  Using cached alembic-1.20.0-py3-none-any.whl.metadata (7.3 kB)
Collecting cryptography<51,>=43.0.0 (from mlflow>=3.1)
  Downloading cryptography-50.0.1-cp311-abi3-macosx_11_0_arm64.whl.metadata (4.3 kB)
Collecting docker<8,>=4.0.0 (from mlflow>=3.1)
  Downloading docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow>=3.1)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<27 (from mlflow>=3.1)
  Downloading gunicorn-26.2.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<4,>=2.5.4 (from mlflow>=3.1)
  Downloading huey-3.4.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: matplotlib<4 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow>=3.1) (3.10.8)
Requirement already satisfied: numpy<3 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow>=3.1) (2.4.2)
Requirement already satisfied: pandas<4 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow>=3.1) (3.0.0)
Requirement already satisfied: pyarrow<26,>=4.0.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow>=3.1) (25.0.1)
Requirement already satisfied: scikit-learn<2 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow>=3.1) (1.9.0)
Requirement already satisfied: scipy<2 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow>=3.1) (1.16.3)
Collecting skops<1 (from mlflow>=3.1)
  Downloading skops-0.15.0-py3-none-any.whl.metadata (4.3 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow>=3.1)
  Downloading sqlalchemy-2.0.54-cp314-cp314-macosx_11_0_arm64.whl.metadata (9.7 kB)
Requirement already satisfied: anyio!=4.15.0,<5,>=3.6.2 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (4.10.0)
Collecting cachetools<8,>=5.0.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading cachetools-7.2.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (8.5.0)
Collecting cloudpickle<4 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading databricks_sdk-0.140.0-py3-none-any.whl.metadata (44 kB)
Requirement already satisfied: fastapi<1 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (0.141.1)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading gitpython-3.1.62-py3-none-any.whl.metadata (13 kB)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading importlib_metadata-9.0.1-py3-none-any.whl.metadata (4.5 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading opentelemetry_api-1.44.0-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading opentelemetry_proto-1.44.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading opentelemetry_sdk-1.44.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging<27 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (25.0)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading protobuf-7.36.2-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Requirement already satisfied: pydantic<3,>=2.0.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (2.13.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (1.2.3)
Requirement already satisfied: pyyaml<7,>=5.1 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (2.32.5)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading sqlparse-0.6.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: starlette<2 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (1.6.0)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (4.15.0)
Requirement already satisfied: uvicorn<1 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from mlflow-skinny==3.16.1->mlflow>=3.1) (0.52.4)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4,>=3.7.0->mlflow>=3.1)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4,>=3.7.0->mlflow>=3.1)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from aiohttp<4,>=3.7.0->mlflow>=3.1) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4,>=3.7.0->mlflow>=3.1)
  Downloading frozenlist-1.8.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.7.0->mlflow>=3.1)
  Downloading multidict-6.9.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4,>=3.7.0->mlflow>=3.1)
  Downloading propcache-0.5.4-cp314-cp314-macosx_11_0_arm64.whl.metadata (25 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4,>=3.7.0->mlflow>=3.1)
  Downloading yarl-1.25.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (111 kB)
Collecting Mako (from alembic!=1.10.0,<2->mlflow>=3.1)
  Using cached mako-1.4.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: idna>=2.8 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from anyio!=4.15.0,<5,>=3.6.2->mlflow-skinny==3.16.1->mlflow>=3.1) (3.11)
Requirement already satisfied: sniffio>=1.1 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from anyio!=4.15.0,<5,>=3.6.2->mlflow-skinny==3.16.1->mlflow>=3.1) (1.3.1)
Requirement already satisfied: cffi>=2.0.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from cryptography<51,>=43.0.0->mlflow>=3.1) (2.0.0)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading google_auth-2.58.0-py3-none-any.whl.metadata (6.0 kB)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.1->mlflow>=3.1) (2.6.3)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from fastapi<1->mlflow-skinny==3.16.1->mlflow>=3.1) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from fastapi<1->mlflow-skinny==3.16.1->mlflow>=3.1) (0.0.5)
Collecting blinker>=1.9.0 (from Flask<4->mlflow>=3.1)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow>=3.1)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=3.1.2 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from Flask<4->mlflow>=3.1) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from Flask<4->mlflow>=3.1) (3.0.2)
Collecting werkzeug>=3.1.0 (from Flask<4->mlflow>=3.1)
  Downloading werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow>=3.1)
  Downloading graphql_core-3.2.12-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow>=3.1)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from graphene<4->mlflow>=3.1) (2.9.0.post0)
Collecting zipp>=3.20 (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from matplotlib<4->mlflow>=3.1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from matplotlib<4->mlflow>=3.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from matplotlib<4->mlflow>=3.1) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from matplotlib<4->mlflow>=3.1) (1.4.9)
Requirement already satisfied: pillow>=8 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from matplotlib<4->mlflow>=3.1) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from matplotlib<4->mlflow>=3.1) (3.2.5)
Collecting opentelemetry-semantic-conventions==0.65b0 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading opentelemetry_semantic_conventions-0.65b0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.1->mlflow>=3.1) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.1->mlflow>=3.1) (2.46.5)
Requirement already satisfied: six>=1.5 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow>=3.1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.1->mlflow>=3.1) (3.4.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.1->mlflow>=3.1) (2026.6.17)
Requirement already satisfied: joblib>=1.4.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from scikit-learn<2->mlflow>=3.1) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from scikit-learn<2->mlflow>=3.1) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from scikit-learn<2->mlflow>=3.1) (3.5.0)
Collecting prettytable>=3.9 (from skops<1->mlflow>=3.1)
  Downloading prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: h11>=0.8 in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from uvicorn<1->mlflow-skinny==3.16.1->mlflow>=3.1) (0.16.0)
Requirement already satisfied: pycparser in /Users/Tari/miniconda3/envs/ml_env/lib/python3.14/site-packages (from cffi>=2.0.0->cryptography<51,>=43.0.0->mlflow>=3.1) (2.23)
Collecting wcwidth>=0.3.5 (from prettytable>=3.9->skops<1->mlflow>=3.1)
  Downloading wcwidth-0.8.4-py3-none-any.whl.metadata (23 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.1->mlflow>=3.1)
  Downloading pyasn1-0.6.4-py3-none-any.whl.metadata (8.4 kB)
Downloading mlflow-3.16.1-py3-none-any.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 517.6 kB/s  0:00:22 eta 0:00:01[36m0:00:01
Downloading mlflow_skinny-3.16.1-py3-none-any.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 232.3 kB/s  0:00:15241.8 kB/s eta 0:00:01
Downloading mlflow_tracing-3.16.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 145.8 kB/s  0:00:13131.9 kB/s eta 0:00:02
Downloading aiohttp-3.14.3-cp314-cp314-macosx_11_0_arm64.whl (512 kB)
Using cached alembic-1.20.0-py3-none-any.whl (268 kB)
Downloading cachetools-7.2.0-py3-none-any.whl (16 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading cryptography-50.0.1-cp311-abi3-macosx_11_0_arm64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 642.2 kB/s  0:00:06a 0:00:01m eta 0:00:01
Downloading databricks_sdk-0.140.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 327.7 kB/s  0:00:03352.4 kB/s eta 0:00:01
Downloading docker-7.2.0-py3-none-any.whl (148 kB)
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading gitpython-3.1.62-py3-none-any.whl (222 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading google_auth-2.58.0-py3-none-any.whl (262 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.12-py3-none-any.whl (216 kB)
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading gunicorn-26.2.0-py3-none-any.whl (228 kB)
Downloading huey-3.4.0-py3-none-any.whl (136 kB)
Downloading importlib_metadata-9.0.1-py3-none-any.whl (27 kB)
Downloading multidict-6.9.0-cp314-cp314-macosx_11_0_arm64.whl (53 kB)
Downloading opentelemetry_api-1.44.0-py3-none-any.whl (60 kB)
Downloading opentelemetry_proto-1.44.0-py3-none-any.whl (72 kB)
Downloading opentelemetry_sdk-1.44.0-py3-none-any.whl (137 kB)
Downloading opentelemetry_semantic_conventions-0.65b0-py3-none-any.whl (204 kB)
Downloading protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
Downloading skops-0.15.0-py3-none-any.whl (144 kB)
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Downloading sqlalchemy-2.0.54-cp314-cp314-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 277.8 kB/s  0:00:07288.2 kB/s eta 0:00:02
Downloading sqlparse-0.6.0-py3-none-any.whl (50 kB)
Downloading yarl-1.25.1-cp314-cp314-macosx_11_0_arm64.whl (104 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading frozenlist-1.8.0-cp314-cp314-macosx_11_0_arm64.whl (49 kB)
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading prettytable-3.18.0-py3-none-any.whl (37 kB)
Downloading propcache-0.5.4-cp314-cp314-macosx_11_0_arm64.whl (51 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pyasn1-0.6.4-py3-none-any.whl (84 kB)
Downloading wcwidth-0.8.4-py3-none-any.whl (299 kB)
Downloading werkzeug-3.1.8-py3-none-any.whl (226 kB)
Downloading zipp-4.1.0-py3-none-any.whl (10 kB)
Using cached mako-1.4.1-py3-none-any.whl (80 kB)
Installing collected packages: huey, zipp, werkzeug, wcwidth, sqlparse, sqlalchemy, smmap, pyasn1, protobuf, propcache, opentelemetry-api, multidict, Mako, itsdangerous, gunicorn, graphql-core, frozenlist, cloudpickle, cachetools, blinker, aiohappyeyeballs, yarl, pyasn1-modules, prettytable, opentelemetry-semantic-conventions, opentelemetry-proto, importlib_metadata, graphql-relay, gitdb, Flask, docker, cryptography, alembic, aiosignal, skops, opentelemetry-sdk, graphene, google-auth, gitpython, Flask-CORS, aiohttp, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
  Attempting uninstall: wcwidth2;249;38;114m╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/45 [werkzeug]
    Found existing installation: wcwidth 0.2.1438;5;237m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/45 [werkzeug]
    Uninstalling wcwidth-0.2.14:;38;114m╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/45 [werkzeug]
      Successfully uninstalled wcwidth-0.2.14━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/45 [werkzeug]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45/45 [mlflow]45 [mlflow]45 [mlflow-skinny]]uth]es]
Successfully installed Flask-3.1.3 Flask-CORS-6.0.5 Mako-1.4.1 aiohappyeyeballs-2.7.1 aiohttp-3.14.3 aiosignal-1.4.0 alembic-1.20.0 blinker-1.9.0 cachetools-7.2.0 cloudpickle-3.1.2 cryptography-50.0.1 databricks-sdk-0.140.0 docker-7.2.0 frozenlist-1.8.0 gitdb-4.0.12 gitpython-3.1.62 google-auth-2.58.0 graphene-3.4.3 graphql-core-3.2.12 graphql-relay-3.2.0 gunicorn-26.2.0 huey-3.4.0 importlib_metadata-9.0.1 itsdangerous-2.2.0 mlflow-3.16.1 mlflow-skinny-3.16.1 mlflow-tracing-3.16.1 multidict-6.9.0 opentelemetry-api-1.44.0 opentelemetry-proto-1.44.0 opentelemetry-sdk-1.44.0 opentelemetry-semantic-conventions-0.65b0 prettytable-3.18.0 propcache-0.5.4 protobuf-6.33.6 pyasn1-0.6.4 pyasn1-modules-0.4.2 skops-0.15.0 smmap-5.0.3 sqlalchemy-2.0.54 sqlparse-0.6.0 wcwidth-0.8.4 werkzeug-3.1.8 yarl-1.25.1 zipp-4.1.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-25.0.1-cp314-cp314-macosx_12_0_arm64.whl.metadata (3.0 kB)
Downloading pyarrow-25.0.1-cp314-cp314-macosx_12_0_arm64.whl (35.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.9/35.9 MB 5.4 MB/s  0:00:07 eta 0:00:01[36m0:00:01
Installing collected packages: pyarrow
Successfully installed pyarrow-25.0.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
preprocessed_df = pd.read_csv('../cleaned_csv/cleaned_data_with_no_pdg.csv')

In [5]:
preprocessed_df["class"].value_counts()

class
5.0      352058
0.0      242892
101.0    175457
3.0      148625
1.0       96982
107.0     76535
108.0     43177
4.0       41585
105.0     35300
8.0       20163
2.0       11609
7.0        3625
102.0      2189
6.0         417
106.0       152
Name: count, dtype: int64

In [84]:
custom_weight = {
    0: 1,
    1: 1,
    2: 1,
    3: 1,
    4: 1,
    5: 1,
    6: 2,
    7: 1,
    8: 1,
    101: 1,
    102: 4,
    105: 1,
    106: 2,
    107: 1,
    108: 1
}

In [6]:
custom_weight_transient = {
    0:   1.0,
    101: 1.0,
    102: 2.0,
    105: 1.0,
    106: 4.0,
    107: 1.0,
    108: 1.0,
}

## Phase two : Define the actual ML Problem
### Train models using 3 datasets: 
* Current Dataset
* Dataset without class 3 and 4
* Dataset without permanent faults

In [5]:
preprocessed_df.isna().sum()

timestamp             0
P-TPT                 0
T-TPT                 0
P-MON-CKP             0
T-JUS-CKP             0
                     ..
P_MON_CKP_slope_60    0
P_TPT_std_60          0
T_TPT_std_60          0
all_stable            0
stability_streak      0
Length: 63, dtype: int64

In [42]:
#---------------------------------
# VISUALIZATION PURPOSES ONLY
#----------------------------------

# Split data into X and Y.
X = preprocessed_df.drop(columns=["class","Instance_id"])
X = X.set_index("timestamp")
y = preprocessed_df["class"]
group = preprocessed_df["Instance_id"]

# Use StratifiedGroupKFold to split data into training and testing.
sgkf = StratifiedGroupKFold(n_splits=2) # can be changed.

for i, (train_idx, test_idx) in enumerate(sgkf.split(X,y,preprocessed_df["Instance_id"])):
    print(f"\n--- Fold {i + 1} ---")
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    groups_train, groups_test = group.iloc[train_idx], group.iloc[test_idx]

    print(f"Train Group IDs: {np.unique(groups_train)} | Test Group IDs: {np.unique(groups_test)}")
    cleared_obj = gc.collect()
    
print(f"Cleared {cleared_obj} trapped objects from RAM")

--- Fold 1 ---
Train Group IDs: ['0_WELL-00001_20170201020207' '0_WELL-00001_20170201120124'
 '0_WELL-00001_20170218060218' '0_WELL-00001_20170218160135'
 '0_WELL-00001_20170218210311' '0_WELL-00001_20170219070031'
 '0_WELL-00001_20170219120021' '0_WELL-00001_20170219220332'
 '0_WELL-00001_20170422040000' '0_WELL-00001_20170424180042'
 '0_WELL-00001_20170425040207' '0_WELL-00001_20170521050000'
 '0_WELL-00001_20170521200000' '0_WELL-00001_20170522010000'
 '0_WELL-00001_20170522110000' '0_WELL-00001_20170522160000'
 '0_WELL-00001_20170523020012' '0_WELL-00001_20170523070000'
 '0_WELL-00001_20170523170000' '0_WELL-00001_20170524030000'
 '0_WELL-00001_20170524080000' '0_WELL-00001_20170524130000'
 '0_WELL-00001_20170525090000' '0_WELL-00001_20170525140000'
 '0_WELL-00001_20170525190000' '0_WELL-00001_20170526050000'
 '0_WELL-00001_20170526100000' '0_WELL-00001_20170527010000'
 '0_WELL-00001_20170527060000' '0_WELL-00001_20170527160000'
 '0_WELL-00001_20170527210000' '0_WELL-00001_20170528070000'
 '0_WELL-00001_20170626150123' '0_WELL-00001_20170627010333'
 '0_WELL-00001_20170823050000' '0_WELL-00001_20170823150000'
 '0_WELL-00001_20170823200000' '0_WELL-00001_20170824160000'
 '0_WELL-00001_20170825020000' '0_WELL-00001_20170825120000'
 '0_WELL-00001_20170825220000' '0_WELL-00001_20170826030000'
 '0_WELL-00001_20170826130000' '0_WELL-00001_20170827090000'
 '0_WELL-00001_20170827140000' '0_WELL-00001_20170827190000'
 '0_WELL-00001_20170828000000' '0_WELL-00002_20131212070005'
 '0_WELL-00002_20131214200030' '0_WELL-00002_20170209170152'
 '0_WELL-00002_20170210030033' '0_WELL-00002_20170210080407'
 '0_WELL-00002_20170211040225' '0_WELL-00002_20170211090129'
 '0_WELL-00002_20170211140152' '0_WELL-00002_20170212100203'
 '0_WELL-00002_20170212200429' '0_WELL-00002_20170213010322'
 '0_WELL-00002_20170213110344' '0_WELL-00002_20170213160107'
 '0_WELL-00002_20170213210214' '0_WELL-00002_20170214070141'
 '0_WELL-00002_20170214120056' '0_WELL-00002_20170215030259'
 '0_WELL-00002_20170215080056' '0_WELL-00002_20170215180118'
 '0_WELL-00002_20170216090118' '0_WELL-00002_20170216140152'
 '0_WELL-00002_20170216190214' '0_WELL-00002_20170217050451'
 '0_WELL-00002_20170218010237' '0_WELL-00002_20170218060225'
 '0_WELL-00002_20170218110022' '0_WELL-00002_20170219070129'
 '0_WELL-00002_20170219120152' '0_WELL-00002_20170219170203'
 '0_WELL-00002_20170307200031' '0_WELL-00002_20170308110124'
 '0_WELL-00002_20170308160353' '0_WELL-00002_20170308210218'
 '0_WELL-00002_20170309070218' '0_WELL-00002_20170309220207'
 '0_WELL-00002_20170310030146' '0_WELL-00002_20170310130321'
 '0_WELL-00002_20170310230042' '0_WELL-00002_20170404030000'
 '0_WELL-00002_20170404180000' '0_WELL-00002_20170405090000'
 '0_WELL-00002_20170406000000' '0_WELL-00002_20170406050000'
 '0_WELL-00002_20170406150000' '0_WELL-00002_20170406200000'
 '0_WELL-00002_20170611100000' '0_WELL-00002_20170611150000'
 '0_WELL-00002_20170612010000' '0_WELL-00002_20170613020022'
 '0_WELL-00002_20170613070011' '0_WELL-00002_20170613120000'
 '0_WELL-00002_20170613220000' '0_WELL-00002_20170614030000'
 '0_WELL-00002_20170614180000' '0_WELL-00002_20170615140021'
 '0_WELL-00002_20170615190127' '0_WELL-00002_20170616050043'
 '0_WELL-00002_20170616150211' '0_WELL-00002_20170617160149'
 '0_WELL-00002_20170617220127' '0_WELL-00002_20170618020105'
 '0_WELL-00002_20170618170211' '0_WELL-00002_20170618220043'
 '0_WELL-00002_20170619080054' '0_WELL-00002_20170620040505'
 '0_WELL-00002_20170620140116' '0_WELL-00002_20170620190211'
 '0_WELL-00002_20170621030054' '0_WELL-00002_20170621080422'
 '0_WELL-00002_20170621230054' '0_WELL-00002_20170622040105'
 '0_WELL-00002_20170623000305' '0_WELL-00002_20170623050021'
 '0_WELL-00002_20170623100032' '0_WELL-00002_20170623150127'
 '0_WELL-00002_20170624160054' '0_WELL-00002_20170624210211'
 '0_WELL-00002_20170625070243' '0_WELL-00002_20170625220127'
 '0_WELL-00002_20170626030043' '0_WELL-00002_20170626080149'
 '0_WELL-00002_20170804210000' '0_WELL-00002_20170805020000'
 '0_WELL-00002_20170805120000' '0_WELL-00002_20170805220000'
 '0_WELL-00002_20170806030000' '0_WELL-00002_20170806230000'
 '0_WELL-00002_20170807040000' '0_WELL-00002_20170807090000'
 '0_WELL-00002_20170807140000' '0_WELL-00002_20170808000000'
 '0_WELL-00002_20170808050000' '0_WELL-00002_20170808100000'
 '0_WELL-00002_20170808200026' '0_WELL-00002_20170809110000'
 '0_WELL-00002_20170810020026' '0_WELL-00002_20170810120000'
 '0_WELL-00002_20170810170000' '0_WELL-00002_20170810220000'
 '0_WELL-00002_20170811030000' '0_WELL-00002_20170811230000'
 '0_WELL-00002_20170812040000' '0_WELL-00002_20170813100000'
 '0_WELL-00004_20140807000129' '0_WELL-00004_20140807040137'
 '0_WELL-00004_20140807080055' '0_WELL-00004_20140807100112'
 '0_WELL-00004_20140807160311' '0_WELL-00004_20140807180050'
 '0_WELL-00005_20170331060014' '0_WELL-00005_20170331110000'
 '0_WELL-00005_20170331210112' '0_WELL-00005_20170401020000'
 '0_WELL-00005_20170401170000' '0_WELL-00005_20170401220156'
 '0_WELL-00005_20170402080043' '0_WELL-00005_20170402180043'
 '0_WELL-00005_20170402230127' '0_WELL-00005_20170403140000'
 '0_WELL-00005_20170403190000' '0_WELL-00005_20170516080038'
 '0_WELL-00005_20170516110000' '0_WELL-00005_20170516200038'
 '0_WELL-00005_20170516230000' '0_WELL-00005_20170812140000'
 '0_WELL-00005_20170812170000' '0_WELL-00005_20170812200000'
 '0_WELL-00005_20170813020000' '0_WELL-00005_20170813050000'
 '0_WELL-00005_20170813110000' '0_WELL-00005_20170813140000'
 '0_WELL-00005_20170813200000' '0_WELL-00005_20170814080000'
 '0_WELL-00005_20170814140000' '0_WELL-00005_20170814170000'
 '0_WELL-00005_20170814200000' '0_WELL-00005_20170815080000'
 '0_WELL-00005_20170815140000' '0_WELL-00005_20170815200000'
 '0_WELL-00005_20170815230000' '0_WELL-00005_20170816110000'
 '0_WELL-00005_20170816170000' '0_WELL-00005_20170816230000'
 '0_WELL-00005_20170817020000' '0_WELL-00005_20170817200000'
 '0_WELL-00005_20170830060000' '0_WELL-00005_20170830090000'
 '0_WELL-00005_20170830120000' '0_WELL-00005_20170910030004'
 '0_WELL-00005_20170910050000' '0_WELL-00005_20170910070000'
 '0_WELL-00005_20170910090000' '0_WELL-00006_20170206220031'
 '0_WELL-00006_20170207230207' '0_WELL-00006_20170208040124'
 '0_WELL-00006_20170208090053' '0_WELL-00006_20170208140146'
 '0_WELL-00006_20170209100207' '0_WELL-00006_20170209200114'
 '0_WELL-00006_20170210010135' '0_WELL-00006_20170222150000'
 '0_WELL-00006_20170223010000' '0_WELL-00006_20170223110000'
 '0_WELL-00006_20170223160000' '0_WELL-00006_20170223210000'
 '0_WELL-00006_20170224020000' '0_WELL-00006_20170224120025'
 '0_WELL-00006_20170224170000' '0_WELL-00006_20170506070114'
 '0_WELL-00006_20170506170053' '0_WELL-00006_20170507030249'
 '0_WELL-00006_20170507080124' '0_WELL-00006_20170508040021'
 '0_WELL-00006_20170508090031' '0_WELL-00006_20170508190053'
 '0_WELL-00006_20170509050031' '0_WELL-00006_20170509100135'
 '0_WELL-00006_20170815060000' '0_WELL-00006_20170815160000'
 '0_WELL-00006_20170815210000' '0_WELL-00006_20170816120000'
 '0_WELL-00006_20170816220000' '0_WELL-00006_20170817030000'
 '0_WELL-00006_20170817180000' '0_WELL-00006_20170818090000'
 '0_WELL-00006_20170819050000' '0_WELL-00006_20170819150000'
 '0_WELL-00006_20170819200000' '0_WELL-00006_20170820110000'
 '0_WELL-00006_20170820210000' '0_WELL-00006_20170821020000'
 '0_WELL-00006_20170821120000' '0_WELL-00006_20170821170000'
 '0_WELL-00006_20170822080000' '0_WELL-00006_20170822130000'
 '0_WELL-00006_20170822180000' '0_WELL-00006_20170824000000'
 '0_WELL-00006_20170824050000' '0_WELL-00006_20170824100000'
 '0_WELL-00006_20170825010042' '0_WELL-00006_20170825060135'
 '0_WELL-00006_20170825110249' '0_WELL-00006_20170826020207'
 '0_WELL-00006_20170826070135' '0_WELL-00006_20170826170103'
 '0_WELL-00006_20170827080114' '0_WELL-00006_20170827230218'
 '0_WELL-00006_20170828090311' '0_WELL-00006_20170828140031'
 '0_WELL-00007_20170801200000' '1_DRAWN_00001' '1_DRAWN_00003'
 '1_DRAWN_00005' '1_DRAWN_00006' '1_DRAWN_00008' '1_DRAWN_00010'
 '1_SIMULATED_00001' '1_SIMULATED_00003' '1_SIMULATED_00004'
 '1_SIMULATED_00006' '1_SIMULATED_00008' '1_SIMULATED_00010'
 '1_SIMULATED_00012' '1_SIMULATED_00014' '1_SIMULATED_00016'
 '1_SIMULATED_00018' '1_SIMULATED_00020' '1_SIMULATED_00021'
 '1_SIMULATED_00023' '1_SIMULATED_00026' '1_SIMULATED_00028'
 '1_SIMULATED_00030' '1_SIMULATED_00032' '1_SIMULATED_00034'
 '1_SIMULATED_00036' '1_SIMULATED_00038' '1_SIMULATED_00040'
 '1_SIMULATED_00042' '1_SIMULATED_00045' '1_SIMULATED_00048'
 '1_SIMULATED_00050' '1_SIMULATED_00051' '1_SIMULATED_00053'
 '1_SIMULATED_00055' '1_SIMULATED_00057' '1_SIMULATED_00059'
 '1_SIMULATED_00061' '1_SIMULATED_00063' '1_SIMULATED_00065'
 '1_SIMULATED_00067' '1_SIMULATED_00069' '1_SIMULATED_00071'
 '1_SIMULATED_00072' '1_SIMULATED_00075' '1_SIMULATED_00076'
 '1_SIMULATED_00079' '1_SIMULATED_00081' '1_SIMULATED_00083'
 '1_SIMULATED_00084' '1_SIMULATED_00086' '1_SIMULATED_00088'
 '1_SIMULATED_00090' '1_SIMULATED_00092' '1_SIMULATED_00095'
 '1_SIMULATED_00096' '1_SIMULATED_00099' '1_SIMULATED_00101'
 '1_SIMULATED_00103' '1_SIMULATED_00105' '1_SIMULATED_00107'
 '1_SIMULATED_00109' '1_SIMULATED_00111' '1_SIMULATED_00113'
 '2_SIMULATED_00001' '2_SIMULATED_00003' '2_SIMULATED_00006'
 '2_SIMULATED_00008' '2_SIMULATED_00010' '2_SIMULATED_00012'
 '2_SIMULATED_00014' '2_SIMULATED_00016' '2_WELL-00009_20170313160804'
 '2_WELL-00010_20171218200131' '3_SIMULATED_00003' '3_SIMULATED_00007'
 '3_SIMULATED_00009' '3_SIMULATED_00011' '3_SIMULATED_00012'
 '3_SIMULATED_00013' '3_SIMULATED_00016' '3_SIMULATED_00018'
 '3_SIMULATED_00022' '3_SIMULATED_00024' '3_SIMULATED_00025'
 '3_SIMULATED_00027' '3_SIMULATED_00031' '3_SIMULATED_00033'
 '3_SIMULATED_00034' '3_SIMULATED_00036' '3_SIMULATED_00037'
 '3_SIMULATED_00038' '3_SIMULATED_00040' '3_SIMULATED_00041'
 '3_SIMULATED_00044' '3_SIMULATED_00045' '3_SIMULATED_00046'
 '3_SIMULATED_00048' '3_SIMULATED_00050' '3_SIMULATED_00052'
 '3_SIMULATED_00053' '3_SIMULATED_00055' '3_SIMULATED_00058'
 '3_SIMULATED_00060' '3_SIMULATED_00061' '3_SIMULATED_00063'
 '3_SIMULATED_00065' '3_SIMULATED_00068' '3_SIMULATED_00069'
 '3_SIMULATED_00071' '3_SIMULATED_00072' '3_SIMULATED_00073'
 '3_WELL-00014_20170917150000' '3_WELL-00014_20170917200000'
 '3_WELL-00014_20170918120103' '3_WELL-00014_20170920060228'
 '3_WELL-00014_20170920110053' '3_WELL-00014_20170921100155'
 '3_WELL-00014_20170921150042' '3_WELL-00014_20170922060124'
 '3_WELL-00014_20170922110042' '3_WELL-00014_20170925060042'
 '3_WELL-00014_20170925160218' '3_WELL-00014_20170926020340'
 '3_WELL-00014_20170926070042' '3_WELL-00014_20171028130000'
 '3_WELL-00014_20171028180038' '4_WELL-00001_20170316120203'
 '4_WELL-00001_20170316140000' '4_WELL-00001_20170316160005'
 '4_WELL-00001_20170316200000' '4_WELL-00001_20170317000000'
 '4_WELL-00001_20170317060000' '4_WELL-00001_20170317100000'
 '4_WELL-00001_20170317120000' '4_WELL-00001_20170317160000'
 '4_WELL-00001_20170317200000' '4_WELL-00001_20170318040000'
 '4_WELL-00001_20170318100000' '4_WELL-00001_20170318140000'
 '4_WELL-00001_20170320190146' '4_WELL-00001_20170421160000'
 '4_WELL-00001_20170421200000' '4_WELL-00001_20170421220000'
 '4_WELL-00001_20170626080000' '4_WELL-00002_20131209010000'
 '4_WELL-00002_20131209050000' '4_WELL-00002_20131209070000'
 '4_WELL-00002_20131209110000' '4_WELL-00002_20131212090000'
 '4_WELL-00002_20131214220010' '4_WELL-00002_20131215020010'
 '4_WELL-00002_20131215060030' '4_WELL-00002_20131215100025'
 '4_WELL-00002_20131215160122' '4_WELL-00002_20131215200132'
 '4_WELL-00002_20131215220107' '4_WELL-00002_20140109030025'
 '4_WELL-00002_20140109150010' '4_WELL-00002_20140115160010'
 '4_WELL-00002_20140115180036' '4_WELL-00002_20140119040025'
 '4_WELL-00002_20140119100112' '4_WELL-00002_20140119120010'
 '4_WELL-00002_20140119180015' '4_WELL-00002_20140119200132'
 '4_WELL-00002_20140120000030' '4_WELL-00002_20140120020025'
 '4_WELL-00002_20140120060203' '4_WELL-00002_20140120080122'
 '4_WELL-00002_20140120120234' '4_WELL-00002_20140120180010'
 '4_WELL-00002_20140120200122' '4_WELL-00002_20140121000224'
 '4_WELL-00002_20140121020056' '4_WELL-00002_20140121100056'
 '4_WELL-00002_20140121140132' '4_WELL-00002_20140121160025'
 '4_WELL-00002_20140121180219' '4_WELL-00002_20140122000117'
 '4_WELL-00002_20140122020051' '4_WELL-00002_20140122100112'
 '4_WELL-00002_20140122120030' '4_WELL-00002_20140122140015'
 '4_WELL-00002_20140122180112' '4_WELL-00002_20140123040132'
 '4_WELL-00002_20140123060030' '4_WELL-00002_20140124060010'
 '4_WELL-00002_20140124140041' '4_WELL-00002_20140124160018'
 '4_WELL-00002_20140124180136' '4_WELL-00002_20140124220029'
 '4_WELL-00002_20140125040033' '4_WELL-00002_20140125060245'
 '4_WELL-00002_20140125100025' '4_WELL-00002_20140125140107'
 '4_WELL-00002_20140125180107' '4_WELL-00002_20140125200016'
 '4_WELL-00002_20140126000059' '4_WELL-00002_20140126040133'
 '4_WELL-00002_20140126080146' '4_WELL-00002_20140126160008'
 '4_WELL-00004_20140804220008' '4_WELL-00004_20140805020033'
 '4_WELL-00004_20140805060008' '4_WELL-00004_20140805120107'
 '4_WELL-00004_20140805140016' '4_WELL-00004_20140805160150'
 '4_WELL-00004_20140805200046' '4_WELL-00004_20140806020107'
 '4_WELL-00004_20140806060141' '4_WELL-00004_20140806080215'
 '4_WELL-00004_20140806120038' '4_WELL-00004_20140806180008'
 '4_WELL-00004_20141117110021' '4_WELL-00004_20141117150055'
 '4_WELL-00004_20141117170116' '4_WELL-00004_20141117190021'
 '4_WELL-00004_20141118010042' '4_WELL-00004_20141118030016'
 '4_WELL-00004_20141118110025' '4_WELL-00004_20141118130050'
 '4_WELL-00004_20141118150107' '4_WELL-00004_20141118210016'
 '4_WELL-00005_20170624040025' '4_WELL-00005_20170624060038'
 '4_WELL-00005_20170624080158' '4_WELL-00005_20170624200107'
 '4_WELL-00005_20170624220033' '4_WELL-00005_20170625020059'
 '4_WELL-00005_20170625113000' '4_WELL-00005_20170625133000'
 '4_WELL-00005_20170626090055' '4_WELL-00005_20170626130016'
 '4_WELL-00005_20170626150141' '4_WELL-00005_20170626170050'
 '4_WELL-00005_20170626230232' '4_WELL-00005_20170627030207'
 '4_WELL-00005_20170627050046' '4_WELL-00005_20170627090025'
 '4_WELL-00005_20170627110055' '4_WELL-00005_20170627170112'
 '4_WELL-00005_20170627210038' '4_WELL-00007_20170517210012'
 '4_WELL-00007_20170518010012' '4_WELL-00007_20170518050016'
 '4_WELL-00007_20170518070124' '4_WELL-00007_20170518130103'
 '4_WELL-00007_20170518150021' '4_WELL-00010_20180416080150'
 '4_WELL-00010_20180416160107' '4_WELL-00010_20180416200008'
 '4_WELL-00010_20180416220141' '4_WELL-00010_20180417000055'
 '4_WELL-00010_20180417060046' '4_WELL-00010_20180423000029'
 '4_WELL-00010_20180423020129' '4_WELL-00010_20180423100050'
 '4_WELL-00010_20180423120112' '4_WELL-00010_20180423140025'
 '4_WELL-00010_20180423220016' '4_WELL-00010_20180424000033'
 '4_WELL-00010_20180424060029' '4_WELL-00010_20180424100046'
 '4_WELL-00010_20180424120050' '4_WELL-00010_20180424140033'
 '4_WELL-00010_20180424160129' '4_WELL-00010_20180424200133'
 '4_WELL-00010_20180425020050' '4_WELL-00010_20180425040224'
 '4_WELL-00010_20180425080141' '4_WELL-00010_20180425140016'
 '4_WELL-00010_20180425180046' '4_WELL-00010_20180425200116'
 '4_WELL-00010_20180426020124' '4_WELL-00010_20180426040033'
 '4_WELL-00010_20180426080025' '4_WELL-00010_20180426180103'
 '4_WELL-00010_20180426220116' '4_WELL-00010_20180427000008'
 '4_WELL-00010_20180427020029' '4_WELL-00010_20180427100107'
 '4_WELL-00010_20180427120016' '4_WELL-00010_20180427180042'
 '4_WELL-00010_20180427200340' '4_WELL-00010_20180428000016'
 '4_WELL-00010_20180428040137' '4_WELL-00010_20180428060033'
 '4_WELL-00010_20180428100116' '4_WELL-00010_20180428120207'
 '4_WELL-00010_20180428140249' '4_WELL-00014_20170915110033'
 '4_WELL-00014_20170915170012' '4_WELL-00014_20170915190050'
 '4_WELL-00014_20170915210116' '4_WELL-00014_20170917000042'
 '4_WELL-00014_20170917080112' '4_WELL-00014_20170917120016'
 '4_WELL-00014_20170923180059' '5_SIMULATED_00001' '5_SIMULATED_00002'
 '5_SIMULATED_00003' '5_SIMULATED_00007' '5_SIMULATED_00008'
 '5_SIMULATED_00011' '5_SIMULATED_00012' '5_SIMULATED_00013'
 '5_SIMULATED_00016' '5_SIMULATED_00019' '5_SIMULATED_00022'
 '5_SIMULATED_00023' '5_SIMULATED_00026' '5_SIMULATED_00027'
 '5_SIMULATED_00030' '5_SIMULATED_00031' '5_SIMULATED_00032'
 '5_SIMULATED_00033' '5_SIMULATED_00035' '5_SIMULATED_00037'
 '5_SIMULATED_00039' '5_SIMULATED_00041' '5_SIMULATED_00044'
 '5_SIMULATED_00049' '5_SIMULATED_00051' '5_SIMULATED_00053'
 '5_SIMULATED_00055' '5_SIMULATED_00057' '5_SIMULATED_00059'
 '5_SIMULATED_00060' '5_SIMULATED_00062' '5_SIMULATED_00063'
 '5_SIMULATED_00065' '5_SIMULATED_00067' '5_SIMULATED_00068'
 '5_SIMULATED_00072' '5_SIMULATED_00074' '5_SIMULATED_00076'
 '5_SIMULATED_00079' '5_SIMULATED_00081' '5_SIMULATED_00082'
 '5_SIMULATED_00084' '5_SIMULATED_00087' '5_SIMULATED_00089'
 '5_SIMULATED_00090' '5_SIMULATED_00095' '5_SIMULATED_00097'
 '5_SIMULATED_00099' '5_SIMULATED_00101' '5_SIMULATED_00104'
 '5_SIMULATED_00107' '5_SIMULATED_00109' '5_SIMULATED_00110'
 '5_SIMULATED_00111' '5_SIMULATED_00113' '5_SIMULATED_00115'
 '5_SIMULATED_00117' '5_SIMULATED_00119' '5_SIMULATED_00121'
 '5_SIMULATED_00122' '5_SIMULATED_00124' '5_SIMULATED_00125'
 '5_SIMULATED_00127' '5_SIMULATED_00129' '5_SIMULATED_00131'
 '5_SIMULATED_00134' '5_SIMULATED_00137' '5_SIMULATED_00138'
 '5_SIMULATED_00142' '5_SIMULATED_00144' '5_SIMULATED_00145'
 '5_SIMULATED_00148' '5_SIMULATED_00149' '5_SIMULATED_00151'
 '5_SIMULATED_00155' '5_SIMULATED_00157' '5_SIMULATED_00158'
 '5_SIMULATED_00159' '5_SIMULATED_00161' '5_SIMULATED_00162'
 '5_SIMULATED_00165' '5_SIMULATED_00166' '5_SIMULATED_00168'
 '5_SIMULATED_00170' '5_SIMULATED_00171' '5_SIMULATED_00173'
 '5_SIMULATED_00175' '5_SIMULATED_00176' '5_SIMULATED_00178'
 '5_SIMULATED_00182' '5_SIMULATED_00183' '5_SIMULATED_00185'
 '5_SIMULATED_00187' '5_SIMULATED_00188' '5_SIMULATED_00190'
 '5_SIMULATED_00192' '5_SIMULATED_00194' '5_SIMULATED_00196'
 '5_SIMULATED_00198' '5_SIMULATED_00200' '5_SIMULATED_00205'
 '5_SIMULATED_00206' '5_SIMULATED_00208' '5_SIMULATED_00209'
 '5_SIMULATED_00211' '5_SIMULATED_00213' '5_SIMULATED_00214'
 '5_SIMULATED_00216' '5_SIMULATED_00218' '5_SIMULATED_00220'
 '5_SIMULATED_00221' '5_SIMULATED_00225' '5_SIMULATED_00226'
 '5_SIMULATED_00228' '5_SIMULATED_00230' '5_SIMULATED_00231'
 '5_SIMULATED_00233' '5_SIMULATED_00237' '5_SIMULATED_00238'
 '5_SIMULATED_00240' '5_SIMULATED_00243' '5_SIMULATED_00244'
 '5_SIMULATED_00249' '5_SIMULATED_00250' '5_SIMULATED_00251'
 '5_SIMULATED_00253' '5_SIMULATED_00255' '5_SIMULATED_00257'
 '5_SIMULATED_00260' '5_SIMULATED_00261' '5_SIMULATED_00263'
 '5_SIMULATED_00267' '5_SIMULATED_00269' '5_SIMULATED_00271'
 '5_SIMULATED_00273' '5_SIMULATED_00275' '5_SIMULATED_00277'
 '5_SIMULATED_00279' '5_SIMULATED_00281' '5_SIMULATED_00282'
 '5_SIMULATED_00285' '5_SIMULATED_00286' '5_SIMULATED_00288'
 '5_SIMULATED_00291' '5_SIMULATED_00293' '5_SIMULATED_00294'
 '5_SIMULATED_00296' '5_SIMULATED_00299' '5_SIMULATED_00301'
 '5_SIMULATED_00304' '5_SIMULATED_00305' '5_SIMULATED_00307'
 '5_SIMULATED_00310' '5_SIMULATED_00311' '5_SIMULATED_00312'
 '5_SIMULATED_00316' '5_SIMULATED_00318' '5_SIMULATED_00319'
 '5_SIMULATED_00322' '5_SIMULATED_00323' '5_SIMULATED_00326'
 '5_SIMULATED_00328' '5_SIMULATED_00330' '5_SIMULATED_00331'
 '5_SIMULATED_00334' '5_SIMULATED_00336' '5_SIMULATED_00338'
 '5_SIMULATED_00339' '5_SIMULATED_00341' '5_SIMULATED_00342'
 '5_SIMULATED_00345' '5_SIMULATED_00346' '5_SIMULATED_00348'
 '5_SIMULATED_00351' '5_SIMULATED_00353' '5_SIMULATED_00354'
 '5_SIMULATED_00356' '5_SIMULATED_00358' '5_SIMULATED_00360'
 '5_SIMULATED_00361' '5_SIMULATED_00364' '5_SIMULATED_00366'
 '5_SIMULATED_00367' '5_SIMULATED_00369' '5_SIMULATED_00370'
 '5_SIMULATED_00372' '5_SIMULATED_00376' '5_SIMULATED_00378'
 '5_SIMULATED_00379' '5_SIMULATED_00381' '5_SIMULATED_00385'
 '5_SIMULATED_00387' '5_SIMULATED_00388' '5_SIMULATED_00390'
 '5_SIMULATED_00392' '5_SIMULATED_00394' '5_SIMULATED_00395'
 '5_SIMULATED_00398' '5_SIMULATED_00401' '5_SIMULATED_00402'
 '5_SIMULATED_00405' '5_SIMULATED_00406' '5_SIMULATED_00409'

In [7]:
def ConfusionMatrix(y_test,y_preds, model_name, desc, color="Blues"):
    # Plot confusion matrix
    labels = np.sort(np.unique(y_test))

    cfm = confusion_matrix(y_test, 
                           y_preds, 
                           labels=labels)
    
    disp = ConfusionMatrixDisplay(confusion_matrix=cfm, 
                                  display_labels=labels
                                  )
    
    fig, ax = plt.subplots(figsize=(14, 12))
    disp.plot(ax=ax, colorbar=True, cmap=color)

    plt.tick_params(axis="x", rotation=45)
    plt.title(f'{model_name} Confusion Matrix On Test Data')
    plt.tight_layout()

    filename = f"confusion_matrix_{model_name}_{desc}.png"

    plt.savefig(filename, dpi=130, bbox_inches='tight')

    plt.close(fig)

    return filename

In [8]:
def feature_importance(model,X, model_name, desc, i, feature_dir):

    sorted_indices = np.argsort(model.feature_importances_)[::-1][:25]
    
    # Reorder both the importances and the column names using those indices
    # (Assumes 'X' is your original pandas training DataFrame)
    sorted_importances = model.feature_importances_[sorted_indices]
    sorted_columns = X.columns[sorted_indices]
    
    # 3. Plot a horizontal bar chart
    fig, ax = plt.subplots(figsize=(14, 10))
    
    # Use ax.barh to map values to labels
    ax.barh(sorted_columns, sorted_importances, label="Feature Importances")
    
    ax.set_xlabel("Importance Value") 
    ax.set_ylabel("Features")  
    ax.set_title(f"{model_name} Feature Importance - Fold {i + 1}")       
    ax.invert_yaxis()                  # Puts the highest importance at the top
    ax.legend()
    plt.tight_layout()

    filename = (f"Feature_importance_{model_name}_{desc}_v{i + 1}.png")

    filepath = feature_dir / filename
    
    fig.savefig(
        filepath,
        dpi=150,
        bbox_inches="tight"
    )

    plt.close(fig)

    return filepath

In [39]:
#------------------------------------------#
# REUSABLE FUNCTION FOR MODEL TRAINING
#------------------------------------------#

def run_model(model,model_name,splits,X,y,group,scoring, sample_weight= None):
    start_time = time.perf_counter()
    print(f"Starting running time...")

    #--------- Create Pipeline ------#
    pipe = Pipeline([("simpleImputer", SimpleImputer(strategy="median")),
                      ("RobustScaler", RobustScaler()),
                      (f"{model_name}", model)])
    
    #--------- Instantiate split class -----#
    sgkf = StratifiedGroupKFold(n_splits=splits, shuffle=True, random_state=42)

    cv_splits = list(
    sgkf.split(X, y, group)
    )

       #--------- Pass sample weights to model.fit() -----#
    fit_params = None
    if sample_weight is not None:
        fit_params = {
            f"{model_name}__sample_weight":
            sample_weight
        }
    
    #--------- Execute Cross-Validation -------#
    print(f"Starting {model} cross-validation...")
    cv_scores = cross_validate(
        estimator=pipe,             
        X=X,                 
        y=y,                 
        # groups=group,       
        cv=cv_splits,            
        scoring=scoring,
        return_estimator=True,
        return_train_score=True,
        verbose=0,
        n_jobs=1
    )
 
    #--------- Create a Prediction Array for Comparing and for Confusion Matrix Evaluation -----#
    y_preds = cross_val_predict(estimator=pipe,
                                X=X,
                                y=y,
                                groups=group,
                                cv=sgkf,
                                n_jobs=1,
                                )
    
    #----------- Log results -----------#

    # ---- F1 MACRO ---- #
    print(f"Macro F1 Scores (Test): {cv_scores["test_f1_macro"]}")

    # ---- ACCURACY SCORE ---- #
    print(f"===============\n"
          f"Accuracy score of Test set: {cv_scores["test_accuracy"]}\n" 
          f"Accuracy score of Training set: {cv_scores["train_accuracy"]}\n"
          f"===============")

    # ---- BALANCED ACCURACY ---- #
    print(f"Balanced Accuracy score (Test): {cv_scores["test_balanced_accuracy"]}")

    # ---- RECALL MACRO ---- #
    print(f"Recall Macro score (Test): {cv_scores["test_recall_macro"]}")

    # ---- AVERAGE TEST SCORE USING F1 MACRO ---- #
    print(f"Average Test Score (Test): {(cv_scores["test_f1_macro"].mean() * 100):.2f}%")

    end_time = time.perf_counter()
    execution_time = end_time - start_time 
    print(f"Execution time: {execution_time} seconds")

    gc.collect()
    return (cv_scores, cv_scores["estimator"], y_preds, y)

## Model 1: LightGBM

### Experiment one: Dataset without class 3 and 4

In [11]:
# ========= CREATE A COPY OF THE ORIGINAL DATASET TO WORK WITH =========
df_copy_without_class_3_4 = preprocessed_df.copy()
df_copy_without_class_3_4 = df_copy_without_class_3_4.set_index("timestamp")

In [12]:
#------ Create Dataset without class 3 and 4------#
df_copy_without_class_3_4 = df_copy_without_class_3_4[~df_copy_without_class_3_4["class"].isin([3,4])]

In [13]:
# ======= INSTANTIATE FEATURE AND TARGET LABELS =======#
X_without_3_4 = df_copy_without_class_3_4.drop(columns=["class","Instance_id"])

y_without_3_4 = df_copy_without_class_3_4["class"]

group_without_3_4 = df_copy_without_class_3_4["Instance_id"]

In [14]:
params = {
    "n_estimators": 600,
    "learning_rate": 0.05,
    "num_leaves": 300,
    "max_depth": 12,
    "min_child_samples": 200,
    "class_weight": "balanced",
    "n_jobs": -1,
    "random_state": 42,
}


model = lgb.LGBMClassifier(**params)
model_name = "LightGBM"


splits = 3

scoring = {
    "f1_macro": "f1_macro",
    "accuracy": "accuracy",
    "recall_macro": "recall_macro",
    "balanced_accuracy": "balanced_accuracy"
}

description = "without_class_3_and_4_dataset"

# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_{model_name}")
feature_dir.mkdir(parents=True, exist_ok=True)

with mlflow.start_run(run_name="Lightgbm_tuned_v1_without_class_3_and_4_dataset", description="Trained without class 3 and 4"):
    cv_scores, estimator, y_preds, y = run_model(model,
                                     model_name,
                                     splits,
                                     X_without_3_4,
                                     y_without_3_4,
                                     group_without_3_4,
                                     scoring
                                     )

    #------- Create Feature Importance for each fold -------#
    for i in range(splits):
        model = estimator[i].named_steps[f"{model_name}"]
        feature_path = feature_importance(model,X_without_3_4,model_name, description,i, feature_dir)

        importance_df = pd.DataFrame({
            "Feature": X_without_3_4.columns,
            "Importance": model.feature_importances_
        }).sort_values("Importance", ascending=False)

        csv_path = feature_dir / f"lightgbm_feature_importances_v{i+1}.csv"

        # Save ALL 72 features
        importance_df.to_csv(
            csv_path,
            index=False
        )

        #------- Save Feature Importance plot in Mlflow run ------#
        mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")
        
    # ---------  Confusion Matrix plot ------ #
    cm_path = ConfusionMatrix(y, y_preds, model_name, description)
    mlflow.log_artifact(cm_path)
        
    mlflow.log_params(params)

    mlflow.log_metrics({
        "cv_mean_f1_macro": cv_scores["test_f1_macro"].mean(),
        "cv_std_f1_macro": cv_scores["test_f1_macro"].std(),
        "cv_mean_accuracy": cv_scores["test_accuracy"].mean(),
        "cv_mean_balanced_accuracy": cv_scores["test_balanced_accuracy"].mean(),
        "cv_mean_recall_macro": cv_scores["test_recall_macro"].mean(),
    })

Starting running time...
Starting LGBMClassifier(class_weight='balanced', learning_rate=0.05, max_depth=12,
               min_child_samples=200, n_estimators=600, n_jobs=-1,
               num_leaves=300, random_state=42) cross-validation...
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.040791 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12437
[LightGBM] [Info] Number of data points in the train set: 716260, number of used features: 60
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Info] Start training from score -2.564949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### Experiment two: Current Dataset

In [15]:
df_copy_with_class_3_and_4 = preprocessed_df.copy()
df_copy_with_class_3_and_4  = df_copy_with_class_3_and_4.set_index("timestamp")

In [16]:
# Split data into X and Y.
X_with_class_3_4 = df_copy_with_class_3_and_4.drop(columns=["class","Instance_id"])

y_with_class_3_4 = df_copy_with_class_3_and_4["class"]
group_with_class_3_4 = df_copy_with_class_3_and_4["Instance_id"]

In [17]:
params = {
    "n_estimators": 600,
    "learning_rate": 0.05,
    "num_leaves": 300,
    "max_depth": 12,
    "min_child_samples": 200,
    "class_weight": "balanced",
    "n_jobs": -1,
    "verbose" : 0,
    "random_state": 42,
}


model = lgb.LGBMClassifier(**params)
model_name = "LightGBM"

splits = 3

scoring = {
    "f1_macro": "f1_macro",
    "accuracy": "accuracy",
    "recall_macro": "recall_macro",
    "balanced_accuracy": "balanced_accuracy"
}

description = "with_class_3_and_4_dataset"

# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_{model_name}")
feature_dir.mkdir(parents=True, exist_ok=True)
with mlflow.start_run(run_name="Lightgbm_tuned_v1_with_class_3_and_4_dataset", description="Trained with class 3 and 4"):
        cv_scores, estimator, y_preds, y = run_model(model,
                                            model_name,
                                            splits,
                                            X_with_class_3_4,
                                            y_with_class_3_4,
                                            group_with_class_3_4,
                                            scoring
                                            )
      #------- Create Feature Importance for each fold -------#
        for i in range(splits):
            model = estimator[i].named_steps[f"{model_name}"]
            feature_path =feature_importance(model,X_with_class_3_4,model_name, description,i, feature_dir)
    
            importance_df = pd.DataFrame({
                "Feature": X_with_class_3_4.columns,
                "Importance": model.feature_importances_
            }).sort_values("Importance", ascending=False)
    
            csv_path = feature_dir / f"lightgbm_{description}_feature_importances_v{i+1}.csv"
    
            # Save ALL 72 features
            importance_df.to_csv(
                csv_path,
                index=False
            )
    
        #------- Save Feature Importance plot in Mlflow run ------#
        mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")
            
        # ---------  Confusion Matrix plot ------ #
        cm_path = ConfusionMatrix(y, y_preds, model_name, description)
        mlflow.log_artifact(cm_path)
            
        mlflow.log_params(params)
    
        mlflow.log_metrics({
            "cv_mean_f1_macro": cv_scores["test_f1_macro"].mean(),
            "cv_std_f1_macro": cv_scores["test_f1_macro"].std(),
            "cv_mean_accuracy": cv_scores["test_accuracy"].mean(),
            "cv_mean_balanced_accuracy": cv_scores["test_balanced_accuracy"].mean(),
            "cv_mean_recall_macro": cv_scores["test_recall_macro"].mean(),
        })

Starting running time...
Starting LGBMClassifier(class_weight='balanced', learning_rate=0.05, max_depth=12,
               min_child_samples=200, n_estimators=600, n_jobs=-1,
               num_leaves=300, random_state=42, verbose=0) cross-validation...
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### Experiment three: Dataset without permanent classes

In [10]:
df_copy_with_transient_classes = preprocessed_df.copy()
df_copy_with_transient_classes = df_copy_with_transient_classes.set_index("timestamp")

df_copy_with_transient_classes.sort_index()

classes = [1,2,3,4,5,6,7,8]
df_copy_with_transient_classes = df_copy_with_transient_classes[~df_copy_with_transient_classes["class"].isin(classes)]

In [37]:
X_with_transient = df_copy_with_transient_classes.drop(columns=["class","Instance_id"])
y_with_transient = df_copy_with_transient_classes["class"]
group_with_transient = df_copy_with_transient_classes["Instance_id"]

In [46]:
params = {
    "n_estimators": 600,
    "learning_rate": 0.05,
    "num_leaves": 300,
    "max_depth": 12,
    "min_child_samples": 200,
    "class_weight": "balanced",
    "n_jobs": -1,
    "verbose" : 0,
    "random_state": 42,
}


model = lgb.LGBMClassifier(**params)
model_name = "LightGBM"

splits = 3

scoring = {
    "f1_macro": "f1_macro",
    "accuracy": "accuracy",
    "recall_macro": "recall_macro",
    "balanced_accuracy": "balanced_accuracy"
}

description = "transient_class_only"

# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_{model_name}")
feature_dir.mkdir(parents=True, exist_ok=True)

with mlflow.start_run(run_name="Lightgbm_tuned_v1_with_transient", description="Trained with transient only"):
        cv_scores, estimator, y_preds, y = run_model(model,
                                            model_name,
                                            splits,
                                            X_with_transient,
                                            y_with_transient,
                                            group_with_transient,
                                            scoring
                                            )
        #------- Create Feature Importance for each fold -------#
        for i in range(splits):
            model = estimator[i].named_steps[f"{model_name}"]
            feature_path =feature_importance(model, X_with_transient,model_name, description,i, feature_dir)
    
            importance_df = pd.DataFrame({
                "Feature": X_with_transient.columns,
                "Importance": model.feature_importances_
            }).sort_values("Importance", ascending=False)
    
            csv_path = feature_dir / f"lightgbm_{description}_feature_importances_v{i+1}.csv"
    
            # Save ALL 72 features
            importance_df.to_csv(
                csv_path,
                index=False
            )
    
        #------- Save Feature Importance plot in Mlflow run ------#
        mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")
            
        # ---------  Confusion Matrix plot ------ #
        cm_path = ConfusionMatrix(y, y_preds, model_name, description)
        mlflow.log_artifact(cm_path)

        # --------- Classfication Report ---------#
        report_dict = classification_report(y, y_preds, target_names=y_with_transient.unique().astype(str), output_dict=True)
        report_lightgbm = pd.DataFrame(report_dict).transpose()

        clf_report_path = f"classification_report_{model_name}_{description}.csv"

        report_lightgbm.to_csv(clf_report_path, index=False)

        mlflow.log_artifact(clf_report_path, artifact_path="classification_report")
            
        mlflow.log_params(params)
    
        mlflow.log_metrics({
            "cv_mean_f1_macro": cv_scores["test_f1_macro"].mean(),
            "cv_std_f1_macro": cv_scores["test_f1_macro"].std(),
            "cv_mean_accuracy": cv_scores["test_accuracy"].mean(),
            "cv_mean_balanced_accuracy": cv_scores["test_balanced_accuracy"].mean(),
            "cv_mean_recall_macro": cv_scores["test_recall_macro"].mean(),
        })

Starting running time...
Starting LGBMClassifier(class_weight='balanced', learning_rate=0.05, max_depth=12,
               min_child_samples=200, n_estimators=600, n_jobs=-1,
               num_leaves=300, random_state=42, verbose=0) cross-validation...
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### Observation:

Removing classes 3/4 slightly improves Macro F1 and noticeably improves fold stability, but those classes were not intrinsically difficult. Restricting the problem toward transient detection produces the strongest mean results, although performance becomes much more fold-dependent. Across all formulations, LightGBM consistently relies on temporal dynamics—especially stability duration, pressure changes, and rolling variability across multiple time scales. The dominant classification difficulty appears to be distinguishing permanent fault states from their related transient stages rather than distinguishing completely unrelated fault families.

## Model 2 : RandomForestClassifier

### Experiment one: Current Dataset

In [20]:
X_rf_with_class_3_4 = df_copy_with_class_3_and_4.drop(columns=["class", "Instance_id"])
y_rf_with_class_3_4 = df_copy_with_class_3_and_4["class"]

group_rf_with_class_3_4 = df_copy_with_class_3_and_4["Instance_id"]

In [ ]:
model = RandomForestClassifier(n_jobs=-1, n_estimators=600, min_samples_split=10, class_weight="balanced")

params = {
    "n_estimators": 600,
    "min_samples_split": 10,
    "class_weight": "balanced",
    "n_jobs": -1,
}

model_name = "RandomForest"

splits = 3
scoring = {
    "f1_macro": "f1_macro",
    "accuracy": "accuracy",
    "recall_macro": "recall_macro",
    "balanced_accuracy": "balanced_accuracy"
}

description = "rf_with_dataset_3_4"

# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_{model_name}")
feature_dir.mkdir(parents=True, exist_ok=True)

with mlflow.start_run(run_name="Randomforest_v1_with_dataset_3_and_4", description="Random Forest on dataset"):
        cv_scores, estimator, y_preds, y = run_model(model,
                                            model_name,
                                            splits,
                                            X_rf_with_class_3_4, 
                                            y_rf_with_class_3_4, 
                                            group_rf_with_class_3_4, 
                                            scoring
                                            )
        #------- Create Feature Importance for each fold -------#
        for i in range(splits):
            model = estimator[i].named_steps[f"{model_name}"]
            feature_path =feature_importance(model,X_rf_with_class_3_4,model_name, description,i, feature_dir)
    
            importance_df = pd.DataFrame({
                "Feature": X_rf_with_class_3_4.columns,
                "Importance": model.feature_importances_
            }).sort_values("Importance", ascending=False)
    
            csv_path = feature_dir / f"randomforest_{description}_feature_importances_v{i+1}.csv"
    
            # Save ALL 72 features
            importance_df.to_csv(
                csv_path,
                index=False
            )
    
        #------- Save Feature Importance plot in Mlflow run ------#
        mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")
            
        # ---------  Confusion Matrix plot ------ #
        cm_path = ConfusionMatrix(y, y_preds, model_name, description)
        mlflow.log_artifact(cm_path)
        
        
        mlflow.log_params(params)
    
        mlflow.log_metrics({
            "cv_mean_f1_macro": cv_scores["test_f1_macro"].mean(),
            "cv_std_f1_macro": cv_scores["test_f1_macro"].std(),
            "cv_mean_accuracy": cv_scores["test_accuracy"].mean(),
            "cv_mean_balanced_accuracy": cv_scores["test_balanced_accuracy"].mean(),
            "cv_mean_recall_macro": cv_scores["test_recall_macro"].mean(),
        })

Starting running time...
Starting RandomForestClassifier(class_weight='balanced', min_samples_split=10,
                       n_estimators=600, n_jobs=-1) cross-validation...
Macro F1 Scores (Test): [0.77654455 0.76386583 0.81793289]
===============
Accuracy score of Test set: [0.9100463  0.948707   0.93643558]
Accuracy score of Training set: [0.99967973 0.99971304 0.99974069]
===============
Balanced Accuracy score (Test): [0.7641679  0.75481654 0.81293617]
Recall Macro score (Test): [0.7641679  0.75481654 0.81293617]
Average Test Score (Test): 78.61%
Execution time: 1195.5896481670206 seconds

### Experiment two: Dataset without class 3 and 4

In [22]:
X_rf_df_copy_without_class_3_4 = df_copy_without_class_3_4.drop(columns=["class", "Instance_id"])
y_rf_df_copy_without_class_3_4 = df_copy_without_class_3_4["class"]

group_rf_df_copy_without_class_3_4 = df_copy_without_class_3_4["Instance_id"]

In [23]:
model = RandomForestClassifier(n_jobs=-1, n_estimators=600, min_samples_split=10, class_weight="balanced")

params = {
    "n_estimators": 600,
    "min_samples_split": 10,
    "class_weight": "balanced",
    "n_jobs": -1,
}

model_name = "RandomForest"

splits = 3
scoring = {
    "f1_macro": "f1_macro",
    "accuracy": "accuracy",
    "recall_macro": "recall_macro",
    "balanced_accuracy": "balanced_accuracy"
}

description = "rf_without_dataset_3_4"

# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_{model_name}")
feature_dir.mkdir(parents=True, exist_ok=True)

with mlflow.start_run(run_name="Randomforest_v1_without_dataset_3_and_4", description="Random Forest on dataset"):
        cv_scores, estimator, y_preds, y = run_model(model,
                                            model_name,
                                            splits,
                                            X_rf_df_copy_without_class_3_4, 
                                            y_rf_df_copy_without_class_3_4, 
                                            group_rf_df_copy_without_class_3_4, 
                                            scoring
                                            )
        #------- Create Feature Importance for each fold -------#
        for i in range(splits):
            model = estimator[i].named_steps[f"{model_name}"]
            feature_path =feature_importance(model, X_rf_df_copy_without_class_3_4,model_name, description,i, feature_dir)
    
            importance_df = pd.DataFrame({
                "Feature": X_rf_df_copy_without_class_3_4.columns,
                "Importance": model.feature_importances_
            }).sort_values("Importance", ascending=False)
    
            csv_path = feature_dir / f"randomforest_{description}_feature_importances_v{i+1}.csv"
    
            # Save ALL 72 features
            importance_df.to_csv(
                csv_path,
                index=False
            )
    
        #------- Save Feature Importance plot in Mlflow run ------#
        mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")
            
        # ---------  Confusion Matrix plot ------ #
        cm_path = ConfusionMatrix(y, y_preds, model_name, description)
        mlflow.log_artifact(cm_path)
            
        mlflow.log_params(params)
    
        mlflow.log_metrics({
            "cv_mean_f1_macro": cv_scores["test_f1_macro"].mean(),
            "cv_std_f1_macro": cv_scores["test_f1_macro"].std(),
            "cv_mean_accuracy": cv_scores["test_accuracy"].mean(),
            "cv_mean_balanced_accuracy": cv_scores["test_balanced_accuracy"].mean(),
            "cv_mean_recall_macro": cv_scores["test_recall_macro"].mean(),
        })

Starting running time...
Starting RandomForestClassifier(class_weight='balanced', min_samples_split=10,
                       n_estimators=600, n_jobs=-1) cross-validation...
Macro F1 Scores (Test): [0.74726584 0.82556595 0.80636949]
===============
Accuracy score of Test set: [0.89863373 0.95954947 0.95014647]
Accuracy score of Training set: [0.9996007  0.99967239 0.99968555]
===============
Balanced Accuracy score (Test): [0.73429012 0.82601118 0.8035715 ]
Recall Macro score (Test): [0.73429012 0.82601118 0.8035715 ]
Average Test Score (Test): 79.31%
Execution time: 854.74375891604 seconds

### Experiment three: Dataset without permanent classes

In [18]:
X_rf_transient = df_copy_with_transient_classes.drop(columns=["Instance_id", "class"])
y_rf_transient = df_copy_with_transient_classes["class"]

group_rf_transient = df_copy_with_transient_classes["Instance_id"]

In [21]:
model = RandomForestClassifier(n_jobs=-1, n_estimators=600, min_samples_split=10, class_weight="balanced")

params = {
    "n_estimators": 600,
    "min_samples_split": 10,
    "class_weight": custom_weight_transient,
    "n_jobs": -1,
}

model_name = "RandomForest"

splits = 3
scoring = {
    "f1_macro": "f1_macro",
    "accuracy": "accuracy",
    "recall_macro": "recall_macro",
    "balanced_accuracy": "balanced_accuracy"
}

description = "rf_with_transient"

# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_{model_name}")
feature_dir.mkdir(parents=True, exist_ok=True)

with mlflow.start_run(run_name="Randomforest_v1_with_transient", description="Random Forest on dataset"):
        cv_scores, estimator, y_preds, y = run_model(model,
                                            model_name,
                                            splits,
                                            X_rf_transient, 
                                            y_rf_transient, 
                                            group_rf_transient, 
                                            scoring
                                            )
        #------- Create Feature Importance for each fold -------#
        for i in range(splits):
            model = estimator[i].named_steps[f"{model_name}"]
            feature_path =feature_importance(model,X_rf_transient,model_name, description,i, feature_dir)
    
            importance_df = pd.DataFrame({
                "Feature": X_rf_transient.columns,
                "Importance": model.feature_importances_
            }).sort_values("Importance", ascending=False)
    
            csv_path = feature_dir / f"randomforest_{description}_feature_importances_v{i+1}.csv"
    
            # Save ALL 72 features
            importance_df.to_csv(
                csv_path,
                index=False
            )
    
        #------- Save Feature Importance plot in Mlflow run ------#
        mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")
            
        # ---------  Confusion Matrix plot ------ #
        cm_path = ConfusionMatrix(y, y_preds, model_name, description)
        mlflow.log_artifact(cm_path)

        # --------- Classfication Report ---------#
        report_dict = classification_report(y, y_preds, target_names=y_with_transient.unique().astype(str), output_dict=True)
        report_rf = pd.DataFrame(report_dict).transpose()

        clf_report_path = f"classification_report_{model_name}_{description}.csv"
        
        report_lightgbm.to_csv(clf_report_path, index=False)
            
        mlflow.log_params(params)
    
        mlflow.log_metrics({
            "cv_mean_f1_macro": cv_scores["test_f1_macro"].mean(),
            "cv_std_f1_macro": cv_scores["test_f1_macro"].std(),
            "cv_mean_accuracy": cv_scores["test_accuracy"].mean(),
            "cv_mean_balanced_accuracy": cv_scores["test_balanced_accuracy"].mean(),
            "cv_mean_recall_macro": cv_scores["test_recall_macro"].mean(),
        })

Starting running time...
Starting RandomForestClassifier(class_weight='balanced', min_samples_split=10,
                       n_estimators=600, n_jobs=-1) cross-validation...
Macro F1 Scores (Test): [0.83205004 0.83583876 0.83864753]
===============
Accuracy score of Test set: [0.90828432 0.97082735 0.9772477 ]
Accuracy score of Training set: [0.99995831 0.99995829 0.99995574]
===============
Balanced Accuracy score (Test): [0.8100873  0.8365189  0.83352594]
Recall Macro score (Test): [0.8100873  0.8365189  0.83352594]
Average Test Score (Test): 83.55%
Execution time: 362.48843341699103 seconds

### observation:
Random Forest reproduces most of the same class-level difficulties seen with LightGBM, particularly classes 7, 106, and 107, which suggests those confusions are rooted in the dataset/problem rather than one algorithm. It performs consistently below LightGBM in Macro F1 and shows an extremely large train/test fit gap. Its feature-importance profile is more distributed than LightGBM's and relies more heavily on raw/rolling temperature levels and, notably, calendar-month features. The transient-focused formulation again produces the strongest overall results, but class-specific weaknesses remain hidden beneath the high aggregate accuracy.

## MODEL 3 : XGBOOST

In [25]:
custom_weight_xgb = {
    0:   1.0,
    1: 1.0,
    2: 2.0,
    3: 1.0,
    4: 4.0,
    5: 1.0,
    6: 1.0,
}

### Experiment one: Current Dataset

In [65]:
X_xgb_with_class_3_4 = df_copy_with_class_3_and_4.drop(columns=["class", "Instance_id"])
y_xgb_with_class_3_4 = df_copy_with_class_3_and_4["class"]

group_xgb_with_class_3_4 = df_copy_with_class_3_and_4["Instance_id"]

In [66]:
#--------- Encode Class Labels ---------#
le_xgb_with_class_3_4 = LabelEncoder()

y_xgb_with_class_3_4_encoded = pd.Series(
    le_xgb_with_class_3_4.fit_transform(
        y_xgb_with_class_3_4
    ),
    index=y_xgb_with_class_3_4.index,
    name="class"
)

print(
    dict(
        zip(
            le_xgb_with_class_3_4.classes_,
            le_xgb_with_class_3_4.transform(
                le_xgb_with_class_3_4.classes_
            )
        )
    )
)

{np.float64(0.0): np.int64(0), np.float64(1.0): np.int64(1), np.float64(2.0): np.int64(2), np.float64(3.0): np.int64(3), np.float64(4.0): np.int64(4), np.float64(5.0): np.int64(5), np.float64(6.0): np.int64(6), np.float64(7.0): np.int64(7), np.float64(8.0): np.int64(8), np.float64(101.0): np.int64(9), np.float64(102.0): np.int64(10), np.float64(105.0): np.int64(11), np.float64(106.0): np.int64(12), np.float64(107.0): np.int64(13), np.float64(108.0): np.int64(14)}

In [67]:
#--------- Compute Sample Weights ---------#
weights_xgb_with_class_3_4 = (
    compute_sample_weight(
        class_weight="balanced",
        y=y_xgb_with_class_3_4_encoded
    )
)

In [68]:
params_xgb_with_class_3_4 = {
    "objective": "multi:softprob",
    "tree_method": "hist",
    "num_class": len(
        le_xgb_with_class_3_4.classes_
    ),
    "eval_metric": "mlogloss",
    "random_state": 42
}


XGB_with_class_3_4 = xgb.XGBClassifier(
    **params_xgb_with_class_3_4
)

model_name = "XGBoost"

description = "with_class_3_and_4_dataset"

In [ ]:
# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_XGBoost")
feature_dir.mkdir(parents=True, exist_ok=True)

splits = 3

with mlflow.start_run(
    run_name="XGBoost_with_class_3_and_4",
    description="XGBoost trained with classes 3 and 4"
):

    cv_scores_xgb_1, estimators_xgb_1, y_preds_xgb_1, y_true_xgb_1 = (
        run_model(
            XGB_with_class_3_4,
            model_name,
            splits,
            X_xgb_with_class_3_4,
            y_xgb_with_class_3_4_encoded,
            group_xgb_with_class_3_4,
            scoring,
            weights_xgb_with_class_3_4
        )
    )

    #------- Create Feature Importance for each fold -------#
    for i in range(splits):
        model = estimators_xgb_1[i].named_steps[f"{model_name}"]
        feature_path =feature_importance(model,X_xgb_with_class_3_4,model_name, description,i, feature_dir)

        importance_df = pd.DataFrame({
            "Feature": X_xgb_with_class_3_4.columns,
            "Importance": model.feature_importances_
        }).sort_values("Importance", ascending=False)

        csv_path = feature_dir / f"xgboost_{description}_feature_importances_v{i+1}.csv"

        # Save ALL 72 features
        importance_df.to_csv(
            csv_path,
            index=False
        )

    #------- Save Feature Importance plot in Mlflow run ------#
    mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")


    y_true_xgb_1_original = (
    le_xgb_with_class_3_4.inverse_transform(
        np.asarray(y_true_xgb_1).astype(int)
    )
    )

    y_preds_xgb_1_original = (
        le_xgb_with_class_3_4.inverse_transform(
            np.asarray(y_preds_xgb_1).astype(int)
        )
    )

    cmf = ConfusionMatrix(y_true_xgb_1_original, y_preds_xgb_1_original, "XGBoost", "with_class_3_4")
    mlflow.log_artifact(cm_path)

    mlflow.log_params(
        params_xgb_with_class_3_4
    )

    mlflow.log_metrics({
        "cv_mean_f1_macro":
            cv_scores_xgb_1["test_f1_macro"].mean(),

        "cv_std_f1_macro":
            cv_scores_xgb_1["test_f1_macro"].std(),

        "cv_mean_accuracy":
            cv_scores_xgb_1["test_accuracy"].mean(),

        "cv_mean_balanced_accuracy":
            cv_scores_xgb_1[
                "test_balanced_accuracy"
            ].mean(),

        "cv_mean_recall_macro":
            cv_scores_xgb_1[
                "test_recall_macro"
            ].mean()
    })

Starting running time...
Starting XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=15, ...) cross-validation...
Macro F1 Scores (Test): [0.73851588 0.23682496 0.72966529]
===============
Accuracy score of Test set: [0.95309174 0.53977023 0.93983887]
Accuracy score of Training set: [0.99833577 0.53691117 0.96441266]
===============
Balanced Accuracy score (Test): [0.73898785 0.24800465 0.73556862]
Recall Macro score (Test): [0.73898785 0.24800465 0.73556862]
Average Test Score (Test): 56.83%
Execution time: 189.06920416699722 seconds

### Experiment two: Without classes 3 and 4

In [70]:
X_xgb_without_class_3_4 = df_copy_without_class_3_4.drop(columns=["class","Instance_id"])

y_xgb_without_class_3_4 = df_copy_without_class_3_4["class"]

group_xgb_without_class_3_4 = df_copy_without_class_3_4["Instance_id"]

In [71]:
#--------- Encode Labels ---------#
le_xgb_without_class_3_4 = LabelEncoder()

y_xgb_without_class_3_4_encoded = pd.Series(
    le_xgb_without_class_3_4.fit_transform(
        y_xgb_without_class_3_4
    ),
    index=y_xgb_without_class_3_4.index,
    name="class"
)

In [72]:
#--------- Compute Sample Weights ---------#
weights_xgb_without_class_3_4 = (
    compute_sample_weight(
        class_weight="balanced",
        y=y_xgb_without_class_3_4_encoded
    )
)

In [73]:
params_xgb_without_class_3_4 = {
    "objective": "multi:softprob",
    "tree_method": "hist",
    "num_class": len(
        le_xgb_without_class_3_4.classes_
    ),
    "eval_metric": "mlogloss",
    "random_state": 42
}


XGB_without_class_3_4 = xgb.XGBClassifier(
    **params_xgb_without_class_3_4
)
model_name = "XGBoost"
description = "without_class_3_4"

In [ ]:
# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_XGBoost")
feature_dir.mkdir(parents=True, exist_ok=True)

splits = 3

with mlflow.start_run(run_name="XGBoost_without_class_3_and_4", description="XGBoost trained without classes 3 and 4"):
    cv_scores_xgb_2, estimators_xgb_2, y_preds_xgb_2, y_true_xgb_2 = (
        run_model(
            XGB_without_class_3_4,
            "XGBoost",
            splits,
            X_xgb_without_class_3_4,
            y_xgb_without_class_3_4_encoded,
            group_xgb_without_class_3_4,
            scoring,
            weights_xgb_without_class_3_4
        )
    )
    #------- Create Feature Importance for each fold -------#
    for i in range(splits):
        model = estimators_xgb_2[i].named_steps[f"{model_name}"]
        feature_path =feature_importance(model,X_xgb_without_class_3_4,model_name, description,i, feature_dir)

        importance_df = pd.DataFrame({
            "Feature": X_xgb_without_class_3_4.columns,
            "Importance": model.feature_importances_
        }).sort_values("Importance", ascending=False)

        csv_path = feature_dir / f"xgboost_{description}_feature_importances_v{i+1}.csv"

        # Save ALL 72 features
        importance_df.to_csv(
            csv_path,
            index=False
        )

    #------- Save Feature Importance plot in Mlflow run ------#
    mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")


    #------- Transform the encoded labels back to original ------#
    y_true_xgb_2_original = (
    le_xgb_without_class_3_4.inverse_transform(
        np.asarray(y_true_xgb_2).astype(int)
    )
    )

    y_preds_xgb_2_original = (
        le_xgb_without_class_3_4.inverse_transform(
            np.asarray(y_preds_xgb_2).astype(int)
        )
    )

    #------- Plot Confusion Matrix ------#
    cmf = ConfusionMatrix(y_true_xgb_2_original, y_preds_xgb_2_original, "XGBoost", "without_class_3_4")
    mlflow.log_artifact(cm_path)

    mlflow.log_params(
        params_xgb_without_class_3_4
    )

    mlflow.log_metrics({
        "cv_mean_f1_macro": cv_scores_xgb_2["test_f1_macro"].mean(),
        "cv_std_f1_macro":cv_scores_xgb_2["test_f1_macro"].std(),
        "cv_mean_accuracy":cv_scores_xgb_2["test_accuracy"].mean(),
        "cv_mean_balanced_accuracy":cv_scores_xgb_2["test_balanced_accuracy"].mean(),
        "cv_mean_recall_macro": cv_scores_xgb_2["test_recall_macro"].mean()
    })

Starting running time...
Starting XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=13, ...) cross-validation...
Macro F1 Scores (Test): [0.81604581 0.60959139 0.60783861]
===============
Accuracy score of Test set: [0.94882891 0.90130037 0.91007357]
Accuracy score of Training set: [0.99995114 0.93465224 0.93143789]
===============
Balanced Accuracy score (Test): [0.80868456 0.61466673 0.61572268]
Recall Macro score (Test): [0.80868456 0.61466673 0.61572268]
Average Test Score (Test): 67.78%
Execution time: 135.25589358300203 seconds

### Experiment 3 — Transient fault classes only

In [48]:
X_xgb_transient = df_copy_with_transient_classes.drop(columns=["class","Instance_id"])

y_xgb_transient = df_copy_with_transient_classes["class"]

group_xgb_transient = df_copy_with_transient_classes["Instance_id"]

In [49]:
#--------- Encode Labels ---------#
le_xgb_transient = LabelEncoder()

y_xgb_transient_encoded = pd.Series(
    le_xgb_transient.fit_transform(
        y_xgb_transient
    ),
    index=y_xgb_transient.index,
    name="class"
)


print(
    dict(
        zip(
            le_xgb_transient.classes_,
            le_xgb_transient.transform(
                le_xgb_transient.classes_
            )
        )
    )
)

{np.float64(0.0): np.int64(0), np.float64(101.0): np.int64(1), np.float64(102.0): np.int64(2), np.float64(105.0): np.int64(3), np.float64(106.0): np.int64(4), np.float64(107.0): np.int64(5), np.float64(108.0): np.int64(6)}

In [50]:
#--------- Compute Sample Weights ---------#
weights_xgb_transient = (
    compute_sample_weight(
        class_weight="balanced",
        y=y_xgb_transient_encoded
    )
)


params_xgb_transient = {
    "objective": "multi:softprob",
    "tree_method": "hist",
    "num_class": len(
        le_xgb_transient.classes_
    ),
    "eval_metric": "mlogloss",
    "random_state": 42
}


XGB_transient = xgb.XGBClassifier(**params_xgb_transient)

model_name = "XGBoost"

description = "transient_class"

In [51]:
# -------- CREATE FOLDER TO STORE FEATURE IMPORTANCES ------ #
feature_dir = pathlib.Path(f"Feature_importance_XGBoost")
feature_dir.mkdir(parents=True, exist_ok=True)

splits = 3

with mlflow.start_run(run_name="XGBoost_transient_only", description=("XGBoost trained on normal operation and transient fault classes only")):
    cv_scores_xgb_3, estimators_xgb_3, y_preds_xgb_3, y_true_xgb_3 = (
        run_model(
            XGB_transient,
            "XGBoost",
            splits,
            X_xgb_transient,
            y_xgb_transient_encoded,
            group_xgb_transient,
            scoring,
            weights_xgb_transient
        )
    )

    #------- Create Feature Importance for each fold -------#
    for i in range(splits):
        model = estimators_xgb_3[i].named_steps[f"{model_name}"]
        feature_path =feature_importance(model,X_xgb_transient,model_name, description,i, feature_dir)

        importance_df = pd.DataFrame({
            "Feature": X_xgb_transient.columns,
            "Importance": model.feature_importances_
        }).sort_values("Importance", ascending=False)

        csv_path = feature_dir / f"xgboost_{description}_feature_importances_v{i+1}.csv"

        # Save ALL 72 features
        importance_df.to_csv(
            csv_path,
            index=False
        )

    #------- Save Feature Importance plot in Mlflow run ------#
    mlflow.log_artifact(str(feature_path), artifact_path="feature_importance")


    #------- Transform the encoded labels back to original ------#
    y_true_xgb_3_original = (
    le_xgb_transient.inverse_transform(
        np.asarray(y_true_xgb_3).astype(int)
    )
    )

    y_preds_xgb_3_original = (
        le_xgb_transient.inverse_transform(
            np.asarray(y_preds_xgb_3).astype(int)
        )
    )

    #------- Plot Confusion Matrix ------#
    cmf = ConfusionMatrix(y_true_xgb_3_original, y_preds_xgb_3_original, "XGBoost", "transient")
    mlflow.log_artifact(cm_path)

    # --------- Classfication Report ---------#
    report_dict = classification_report(y_true_xgb_3_original, y_preds_xgb_3_original, target_names=y_xgb_transient.unique().astype(str), output_dict=True)
    report_xgb = pd.DataFrame(report_dict).transpose()

    clf_report_path = f"classification_report_{model_name}_{description}.csv"
    
    report_lightgbm.to_csv(clf_report_path, index=False)

    mlflow.log_params(
        params_xgb_transient
    )

    mlflow.log_metrics({
        "cv_mean_f1_macro": cv_scores_xgb_3["test_f1_macro"].mean(),
        "cv_std_f1_macro": cv_scores_xgb_3["test_f1_macro"].std(),
        "cv_mean_accuracy": cv_scores_xgb_3["test_accuracy"].mean(),
        "cv_mean_balanced_accuracy": cv_scores_xgb_3["test_balanced_accuracy"].mean(),
        "cv_mean_recall_macro": cv_scores_xgb_3["test_recall_macro"].mean()
    })

Starting running time...
Starting XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=7, ...) cross-validation...
Macro F1 Scores (Test): [0.89517641 0.77377954 0.82595813]
===============
Accuracy score of Test set: [0.97564877 0.93350405 0.9788341 ]
Accuracy score of Training set: [0.99999218 0.99110723 0.99998959]
===============
Balanced Accuracy score (Test): [0.88450163 0.7907583  0.8147828 ]
Recall Macro score (Test): [0.88450163 0.7907583  0.8147828 ]
Average Test Score (Test): 83.16%
Execution time: 51.63095349998912 seconds

### Conclusion:

| Model         |    Current | Without 3/4 | Transient-focused |
| ------------- | ---------: | ----------: | ----------------: |
| LightGBM      | **81.62%** |  **83.37%** |        **88.67%** |
| Random Forest | **78.61%** |  **79.31%** |        **84.59%** |
| XGBoost       | **56.83%** |  **67.78%** |        **85.85%** |

#### LightGBM:

→ strongest overall
→ relatively stable
→ very consistent feature families

#### Random Forest
→ slightly weaker
→ heavy train/test fit gap
→ more reliance on raw/rolling temperature and month

#### XGBoost
→ highly unstable on the broader datasets
→ much stronger once the task is narrowed
→ feature importance changes dramatically between folds

In [30]:
report_lightgbm

              precision    recall  f1-score        support
0.0            0.973320  0.741515  0.841750  242892.000000
101.0          0.907915  0.851331  0.878713  175457.000000
102.0          0.485273  0.617177  0.543334    2189.000000
105.0          0.860233  0.662380  0.748452   35300.000000
106.0          0.004145  0.460526  0.008216     152.000000
107.0          0.495945  0.958712  0.653719   76535.000000
108.0          0.975616  0.707970  0.820518   43177.000000
accuracy       0.795943  0.795943  0.795943       0.795943
macro avg      0.671778  0.714230  0.642100  575702.000000
weighted avg   0.881050  0.795943  0.819350  575702.000000

In [31]:
report_rf

              precision    recall  f1-score        support
0.0            0.924203  0.983470  0.952916  242892.000000
101.0          0.983503  0.985358  0.984430  175457.000000
102.0          0.992853  0.888534  0.937801    2189.000000
105.0          0.993909  0.845864  0.913930   35300.000000
106.0          0.541667  0.427632  0.477941     152.000000
107.0          0.934405  0.807591  0.866382   76535.000000
108.0          1.000000  1.000000  1.000000   43177.000000
accuracy       0.952958  0.952958  0.952958       0.952958
macro avg      0.910077  0.848350  0.876200  575702.000000
weighted avg   0.953751  0.952958  0.951974  575702.000000

In [32]:
report_xgb

              precision    recall  f1-score        support
0.0            0.971145  0.982840  0.976958  242892.000000
101.0          0.991194  0.987969  0.989579  175457.000000
102.0          0.984600  0.876199  0.927242    2189.000000
105.0          0.991719  0.990652  0.991185   35300.000000
106.0          0.054487  0.335526  0.093750     152.000000
107.0          0.956253  0.920794  0.938189   76535.000000
108.0          0.999815  0.999328  0.999571   43177.000000
accuracy       0.977294  0.977294  0.977294       0.977294
macro avg      0.849888  0.870473  0.845211  575702.000000
weighted avg   0.978497  0.977294  0.977796  575702.000000